# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bwc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add name', max_length=50)),
                ('description', models.TextField(help_text='Add a full description.')),
                ('Active', models.CharField(default='Yes', help_text='Set status.', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='joined',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 15, 18, 50, 34, 42028)),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 15, 18, 50, 34, 45078)),
        ),
        migrations.AlterField(
            model_name='registered',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 15, 18, 50, 34, 38630)),
        ),
        migrations.AlterField(
            model_name='registered',
            name='payment',
            field=models.ForeignKey(help_text='Add payment method', on_delete=django.db.models.deletion.CASCADE, to='bwc.paymentMethod'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 15, 18, 50, 34, 26600)),
        ),
    ]
